### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by danboid** [intellitrend/zabbixapi-php#1]
I don't understand how this is supposed to work with Zabbix. The installation instructions say:

```
Installation

There is no installation required. Simply copy the file Zabbixapi.php and use the class.
```

If you just did that, I don't see how the PHP server would know how or what to send to the Zabbix server or zabbix agent? I cannot see a Zabbix template to import in this repo so I'm not sure how to hook it up to Zabbix (4.0)?

I want to monitor the health of a PHP server with Zabbix but maybe this doesn't do what I want anyway?

**Comment by intellitrend-team** [comment]
Hello,
`zabbixapi-php` is not intended to monitor a webserver or php/php-fpm itself.

`zabbixapi-php` is to be used to communicate with the Zabbix-API.

More info on the Zabbix API can be found here: https://www.zabbix.com/documentation/4.0/manual/api

> I want to monitor the health of a PHP server with Zabbix but maybe this doesn't do what I want anyway?

No- it is not intended to do this.

**Comment by danboid** [comment]
OK thanks!

I am now using a Zabbix systemd monitoring template to monitor php-fpm:

https://github.com/MogiePete/zabbix-systemd-service-monitoring

**Comment by intellitrend-team** [comment]
Great this works for you - closing now.
