### ISSUE TITLE
adding parameters

### ISSUE THREAD

**Issue by coconutservices** [intellitrend/zabbixapi-php#2]
Love the API, thanks so much. Found a snag, or im just not smart here.

how do i write a call for something where i want to limit it as the API calls out?

I cannot find good examples., say i want to query the current value of a specific item for a specific host? All the examples call a list of values that include all devices.

Thanks!

Jon

**Comment by coconutservices** [comment]
Yes. I am Just uninformed, sorry to bug you.... <quietly walks away>

**Comment by coconutservices** [comment]
for example. how would i write this in the syntax required buy the API?

{
    "jsonrpc": "2.0",
    "method": "item.get",
    "params": {
        "output": "extend",
        "hostids": "10084",
        "search": {
            "key_": "system"
        },
        "sortfield": "name"
    },
    "auth": "038e1d7b1735c6a5436ee9eae095879e",
    "id": 1
}

**Comment by intellitrend-team** [comment]
First of all sorry for the late reply and thank you for using the library.

We made a new commit for version 2.6 and added a new example that shows how to pass filter params. See `examples/filter.php` for details. There is also a new section ` Using filters and field selectors` in the `README.md`.

Please let us know if this answers your questions.

**Comment by intellitrend-team** [comment]
Just a note: Version 2.7 is out. For consistency the classfile was renamed to `ZabbixApi.php`.

**Comment by intellitrend-team** [comment]
Closed
