### ISSUE TITLE
When there's an exception in callZabbixApi, the exception isn't forwarded properly

### ISSUE THREAD

**Issue by daften** [intellitrend/zabbixapi-php#7]
In \IntelliTrend\Zabbix\ZabbixApi::call a generic Exception is caught, and it is assumed this is a problem with authentication. It is then assumed that logging in again will work. But sometimes that is not the cases and there's just something wrong that's not auth. In that case the $response object being returned at the end of \IntelliTrend\Zabbix\ZabbixApi::call is null which triggers an Exception, but with message Notice: Undefined variable: response.

This means all data about the ACTUAL exception thrown when returning from Zabbix, or any data about what went wrong is lost for the application around ZabbixApi.

It would be better to use custom Exception classes for ZabbixApi. E.g. by starting with a ZabbixApiException and then have subclasses of that for specific scenario's, so exceptions can be caught more granular. E.g. a ZabbixApiAuthException in this case. If it's that exception, a second auth can happen. And if it's not that, the ZabbixApiException can just be forwarded.

i don't know if this makes sense?

**Comment by intellitrend-team** [comment]
First of all, sorry for the delay. We will take a look at the exception handling and make some improvements. It definitely makes sense to introduce a custom exception class for this purpose.

We will report back once there's progress.

**Comment by intellitrend-team** [comment]
We have fixed an exception handling problem in `call()` and also introduced a new API exception class as suggested. Both are available in v3.2.0.
